"""init schema

Revision ID: 64af9bceffa9
Revises: 
Create Date: 2025-09-26 15:03:07.263369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64af9bceffa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_campaign',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_dim_campaign'))
    )
    op.create_table('dim_adset',
    sa.Column('adset_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('adset_name', sa.String(length=255), nullable=False),
    sa.Column('bid_strategy', sa.String(length=64), nullable=False),
    sa.Column('daily_budget', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaign.campaign_id'], name=op.f('fk_dim_adset_campaign_id_dim_campaign'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('adset_id', name=op.f('pk_dim_adset'))
    )
    op.create_table('dim_ad',
    sa.Column('ad_id', sa.String(length=32), nullable=False),
    sa.Column('adset_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_name', sa.String(length=255), nullable=False),
    sa.Column('creative_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adset_id'], ['dim_adset.adset_id'], name=op.f('fk_dim_ad_adset_id_dim_adset'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ad_id', name=op.f('pk_dim_ad'))
    )
    op.create_table('fact_insights_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('adset_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_id', sa.String(length=32), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('conversions', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['dim_ad.ad_id'], name=op.f('fk_fact_insights_daily_ad_id_dim_ad'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['adset_id'], ['dim_adset.adset_id'], name=op.f('fk_fact_insights_daily_adset_id_dim_adset'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaign.campaign_id'], name=op.f('fk_fact_insights_daily_campaign_id_dim_campaign'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('date', 'ad_id', name='pk_fact_insights_daily')
    )
    op.create_index('idx_fact_adset_date', 'fact_insights_daily', ['adset_id', 'date'], unique=False)
    op.create_index('idx_fact_campaign_date', 'fact_insights_daily', ['campaign_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_campaign_date', table_name='fact_insights_daily')
    op.drop_index('idx_fact_adset_date', table_name='fact_insights_daily')
    op.drop_table('fact_insights_daily')
    op.drop_table('dim_ad')
    op.drop_table('dim_adset')
    op.drop_table('dim_campaign')
    # ### end Alembic commands ###
